"""empty message

Revision ID: 3dad5c741972
Revises: 7fd91857b19a
Create Date: 2022-01-27 20:02:38.913266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dad5c741972'
down_revision = '7fd91857b19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_email_auth', 'user_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_email_auth', 'user_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
