"""empty message

Revision ID: 9606e57498b7
Revises: d00f7831b0db
Create Date: 2022-01-18 02:49:24.080275

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '9606e57498b7'
down_revision = 'd00f7831b0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=True),
    sa.Column('url_hash', sa.String(length=120), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=datetime.datetime(2022, 1, 18, 2, 49, 23, 989636)), nullable=True),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_email_auth')
    # ### end Alembic commands ###
